#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BigDays.Resource", IsApplication=true)]

namespace BigDays
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010012
			public const int confirm_logout = 2130771986;
			
			// aapt resource value: 0x7f01000c
			public const int done_button_background = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int done_button_text = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int extra_fields = 2130771975;
			
			// aapt resource value: 0x7f010013
			public const int fetch_user_info = 2130771987;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010017
			public const int is_cropped = 2130771991;
			
			// aapt resource value: 0x7f010014
			public const int login_text = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int logout_text = 2130771989;
			
			// aapt resource value: 0x7f01000d
			public const int multi_select = 2130771981;
			
			// aapt resource value: 0x7f010016
			public const int preset_size = 2130771990;
			
			// aapt resource value: 0x7f01000e
			public const int radius_in_meters = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int results_limit = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int search_text = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int show_pictures = 2130771974;
			
			// aapt resource value: 0x7f010011
			public const int show_search_box = 2130771985;
			
			// aapt resource value: 0x7f010008
			public const int show_title_bar = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public const int title_bar_background = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int title_text = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080002
			public const int com_facebook_blue = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int com_facebook_loginview_text_color = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_picker_search_bar_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_picker_search_bar_text = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int xam_blue = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int xam_dark_blue = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int xam_gray = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int xam_green = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int xam_light_gray = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int xam_purple = 2131230727;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_loginview_compound_drawable_padding = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_loginview_padding_bottom = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_padding_left = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_loginview_padding_right = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_loginview_padding_top = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_loginview_text_size = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_picker_divider_width = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_picker_place_image_size = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_profilepictureview_preset_size_large = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_profilepictureview_preset_size_small = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_tooltip_horizontal_padding = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AdBannerDefault = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AddBig = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AddSmall = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int alertbtnbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ArrowRight = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BackgroundLight = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Big_Day_Countdown_icon_app_1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Big_Day_Countdown_icon_appSupper_99_99 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Big_Day_CountdownFree = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int border_buttons = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_custom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int buynow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int colorChart = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_blue = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_blue_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_blue_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_blue_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_check = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_button_check_off = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_button_check_on = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_button_grey_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_button_grey_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_button_grey_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_close = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_inverse_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_list_divider = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_list_section_header_background = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_loginbutton_silver = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_logo = 2130837534;
			
			// aapt resource value: 0x7f02007b
			public const int com_facebook_picker_default_separator_color = 2130837627;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_picker_item_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_picker_list_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_picker_list_longpressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_picker_list_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_picker_list_selector = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_picker_list_selector_background_transition = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_picker_list_selector_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_picker_magnifier = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_picker_top_button = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_place_default_icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_profile_default_icon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_profile_picture_blank_portrait = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_profile_picture_blank_square = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_tooltip_black_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_tooltip_black_bottomnub = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_tooltip_black_topnub = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int com_facebook_tooltip_black_xout = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int com_facebook_tooltip_blue_background = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_tooltip_blue_bottomnub = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int com_facebook_tooltip_blue_topnub = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int com_facebook_tooltip_blue_xout = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int com_facebook_top_background = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int com_facebook_top_button = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Edit = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int editbtnbg = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int EditSmall = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Facebook = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Feedback = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int FeedbackSmall = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_about = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_accept = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_action_cancel = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_action_discard = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_action_download = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_action_edit = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_action_group = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_action_new = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_action_share = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_action_storage = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_action_view_as_list = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_empty = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_error = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_stub = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icon = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Icon62 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Icon99x99 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int img1 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int img10 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int img10small = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int img11 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int img11small = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int img12 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int img12small = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int img13 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int img13small = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int img14 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int img14small = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int img15 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int img15small = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int img16 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int img16small = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int img17 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int img17small = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int img1small = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int img2 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int img2small = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int img3 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int img3small = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int img4 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int img4small = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int img5 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int img5small = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int img6 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int img6small = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int img7 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int img7small = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int img8 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int img8small = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int img9 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int img9small = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int img_help_resize = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int List = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ListSmall = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int Mail = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int Message = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int rotate = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int Save = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int Share = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int ShareSmall = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int splashscreen = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int Twitter = 2130837626;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0021
			public const int AlertOk = 2131361825;
			
			// aapt resource value: 0x7f0a008a
			public const int Alerts = 2131361930;
			
			// aapt resource value: 0x7f0a007f
			public const int BigDayName = 2131361919;
			
			// aapt resource value: 0x7f0a0068
			public const int BigDaysListView = 2131361896;
			
			// aapt resource value: 0x7f0a0088
			public const int CameraBtn = 2131361928;
			
			// aapt resource value: 0x7f0a008c
			public const int CancelOrDelete = 2131361932;
			
			// aapt resource value: 0x7f0a0029
			public const int CountDownDays = 2131361833;
			
			// aapt resource value: 0x7f0a002c
			public const int CountDownHours = 2131361836;
			
			// aapt resource value: 0x7f0a002f
			public const int CountDownMin = 2131361839;
			
			// aapt resource value: 0x7f0a0032
			public const int CountDownSec = 2131361842;
			
			// aapt resource value: 0x7f0a004f
			public const int DefImagesGrid = 2131361871;
			
			// aapt resource value: 0x7f0a0027
			public const int EndDate = 2131361831;
			
			// aapt resource value: 0x7f0a009b
			public const int FacebookBtn = 2131361947;
			
			// aapt resource value: 0x7f0a0074
			public const int Feedback = 2131361908;
			
			// aapt resource value: 0x7f0a0024
			public const int ItemImage = 2131361828;
			
			// aapt resource value: 0x7f0a0078
			public const int MainCountDownDays = 2131361912;
			
			// aapt resource value: 0x7f0a0079
			public const int MainCountDownHours = 2131361913;
			
			// aapt resource value: 0x7f0a007a
			public const int MainCountDownMin = 2131361914;
			
			// aapt resource value: 0x7f0a007b
			public const int MainCountDownSec = 2131361915;
			
			// aapt resource value: 0x7f0a0077
			public const int MainCountDownTitle = 2131361911;
			
			// aapt resource value: 0x7f0a0063
			public const int NewCountDownTitle = 2131361891;
			
			// aapt resource value: 0x7f0a0062
			public const int NewInfoBox = 2131361890;
			
			// aapt resource value: 0x7f0a0070
			public const int NewInfoBoxControl = 2131361904;
			
			// aapt resource value: 0x7f0a005b
			public const int Report = 2131361883;
			
			// aapt resource value: 0x7f0a008b
			public const int SeveOrEdit = 2131361931;
			
			// aapt resource value: 0x7f0a009c
			public const int TwitterBtn = 2131361948;
			
			// aapt resource value: 0x7f0a006f
			public const int adView = 2131361903;
			
			// aapt resource value: 0x7f0a0069
			public const int addBigDays = 2131361897;
			
			// aapt resource value: 0x7f0a0020
			public const int addNewBigDays = 2131361824;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a001c
			public const int alertFiveInd = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int alertFiveIndTitle = 2131361819;
			
			// aapt resource value: 0x7f0a001d
			public const int alertFiveNum = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int alertFiveStr = 2131361822;
			
			// aapt resource value: 0x7f0a0018
			public const int alertForeInd = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int alertForeIndTitle = 2131361815;
			
			// aapt resource value: 0x7f0a0019
			public const int alertForeNum = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int alertForeStr = 2131361818;
			
			// aapt resource value: 0x7f0a000c
			public const int alertOneInd = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int alertOneIndTitle = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int alertOneNum = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int alertOneStr = 2131361806;
			
			// aapt resource value: 0x7f0a0014
			public const int alertThreeInd = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int alertThreeIndTitle = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int alertThreeNum = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int alertThreeStr = 2131361814;
			
			// aapt resource value: 0x7f0a0010
			public const int alertTwoInd = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int alertTwoIndTitle = 2131361807;
			
			// aapt resource value: 0x7f0a0011
			public const int alertTwoNum = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int alertTwoStr = 2131361810;
			
			// aapt resource value: 0x7f0a005f
			public const int btnRotate = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int btnSave = 2131361888;
			
			// aapt resource value: 0x7f0a008e
			public const int button1 = 2131361934;
			
			// aapt resource value: 0x7f0a008f
			public const int button2 = 2131361935;
			
			// aapt resource value: 0x7f0a0046
			public const int com_facebook_body_frame = 2131361862;
			
			// aapt resource value: 0x7f0a0048
			public const int com_facebook_button_xout = 2131361864;
			
			// aapt resource value: 0x7f0a0036
			public const int com_facebook_login_activity_progress_bar = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int com_facebook_picker_activity_circle = 2131361845;
			
			// aapt resource value: 0x7f0a0038
			public const int com_facebook_picker_checkbox = 2131361848;
			
			// aapt resource value: 0x7f0a003c
			public const int com_facebook_picker_checkbox_stub = 2131361852;
			
			// aapt resource value: 0x7f0a0040
			public const int com_facebook_picker_divider = 2131361856;
			
			// aapt resource value: 0x7f0a003f
			public const int com_facebook_picker_done_button = 2131361855;
			
			// aapt resource value: 0x7f0a0039
			public const int com_facebook_picker_image = 2131361849;
			
			// aapt resource value: 0x7f0a003d
			public const int com_facebook_picker_list_section_header = 2131361853;
			
			// aapt resource value: 0x7f0a0034
			public const int com_facebook_picker_list_view = 2131361844;
			
			// aapt resource value: 0x7f0a003a
			public const int com_facebook_picker_profile_pic_stub = 2131361850;
			
			// aapt resource value: 0x7f0a0037
			public const int com_facebook_picker_row_activity_circle = 2131361847;
			
			// aapt resource value: 0x7f0a0045
			public const int com_facebook_picker_search_text = 2131361861;
			
			// aapt resource value: 0x7f0a003b
			public const int com_facebook_picker_title = 2131361851;
			
			// aapt resource value: 0x7f0a0042
			public const int com_facebook_picker_title_bar = 2131361858;
			
			// aapt resource value: 0x7f0a0041
			public const int com_facebook_picker_title_bar_stub = 2131361857;
			
			// aapt resource value: 0x7f0a003e
			public const int com_facebook_picker_top_bar = 2131361854;
			
			// aapt resource value: 0x7f0a0044
			public const int com_facebook_search_bar_view = 2131361860;
			
			// aapt resource value: 0x7f0a004a
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361866;
			
			// aapt resource value: 0x7f0a0049
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361865;
			
			// aapt resource value: 0x7f0a0047
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361863;
			
			// aapt resource value: 0x7f0a004d
			public const int com_facebook_usersettingsfragment_login_button = 2131361869;
			
			// aapt resource value: 0x7f0a004b
			public const int com_facebook_usersettingsfragment_logo_image = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int com_facebook_usersettingsfragment_profile_name = 2131361868;
			
			// aapt resource value: 0x7f0a0081
			public const int dateEdit = 2131361921;
			
			// aapt resource value: 0x7f0a0086
			public const int defImagesBtn = 2131361926;
			
			// aapt resource value: 0x7f0a0065
			public const int editBigDaysBtn = 2131361893;
			
			// aapt resource value: 0x7f0a0089
			public const int editRepeat = 2131361929;
			
			// aapt resource value: 0x7f0a0051
			public const int facebook_login_button = 2131361873;
			
			// aapt resource value: 0x7f0a0057
			public const int fragment_container = 2131361879;
			
			// aapt resource value: 0x7f0a0093
			public const int gridImages = 2131361939;
			
			// aapt resource value: 0x7f0a0061
			public const int helpRelaLayout = 2131361889;
			
			// aapt resource value: 0x7f0a0094
			public const int image = 2131361940;
			
			// aapt resource value: 0x7f0a0084
			public const int imageArea = 2131361924;
			
			// aapt resource value: 0x7f0a0053
			public const int imageView1 = 2131361875;
			
			// aapt resource value: 0x7f0a0076
			public const int infoBox = 2131361910;
			
			// aapt resource value: 0x7f0a0022
			public const int infoBoxListItem = 2131361826;
			
			// aapt resource value: 0x7f0a0003
			public const int large = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int linearLayout1 = 2131361799;
			
			// aapt resource value: 0x7f0a007c
			public const int linearLayout10 = 2131361916;
			
			// aapt resource value: 0x7f0a0064
			public const int linearLayout11 = 2131361892;
			
			// aapt resource value: 0x7f0a007d
			public const int linearLayout12 = 2131361917;
			
			// aapt resource value: 0x7f0a0071
			public const int linearLayout13 = 2131361905;
			
			// aapt resource value: 0x7f0a005e
			public const int linearLayout1311 = 2131361886;
			
			// aapt resource value: 0x7f0a0009
			public const int linearLayout2 = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int linearLayout3 = 2131361800;
			
			// aapt resource value: 0x7f0a0028
			public const int linearLayout4 = 2131361832;
			
			// aapt resource value: 0x7f0a002b
			public const int linearLayout5 = 2131361835;
			
			// aapt resource value: 0x7f0a002e
			public const int linearLayout6 = 2131361838;
			
			// aapt resource value: 0x7f0a0031
			public const int linearLayout7 = 2131361841;
			
			// aapt resource value: 0x7f0a0023
			public const int linearLayout8 = 2131361827;
			
			// aapt resource value: 0x7f0a0025
			public const int linearLayout9 = 2131361829;
			
			// aapt resource value: 0x7f0a0097
			public const int listRepeat = 2131361943;
			
			// aapt resource value: 0x7f0a0073
			public const int mainAddBigDays = 2131361907;
			
			// aapt resource value: 0x7f0a006d
			public const int mainImgBase = 2131361901;
			
			// aapt resource value: 0x7f0a006c
			public const int main_layout = 2131361900;
			
			// aapt resource value: 0x7f0a0050
			public const int main_ui_container = 2131361872;
			
			// aapt resource value: 0x7f0a0026
			public const int name = 2131361830;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int normal = 2131361796;
			
			// aapt resource value: 0x7f0a008d
			public const int numberPicker1 = 2131361933;
			
			// aapt resource value: 0x7f0a0087
			public const int photo_AlbumBtn = 2131361927;
			
			// aapt resource value: 0x7f0a0043
			public const int picker_subtitle = 2131361859;
			
			// aapt resource value: 0x7f0a0085
			public const int pixabayImagesBtn = 2131361925;
			
			// aapt resource value: 0x7f0a0092
			public const int pixabaySearchBtn = 2131361938;
			
			// aapt resource value: 0x7f0a0091
			public const int pixabaySearchText = 2131361937;
			
			// aapt resource value: 0x7f0a0056
			public const int postStatusUpdateButton = 2131361878;
			
			// aapt resource value: 0x7f0a0095
			public const int progress = 2131361941;
			
			// aapt resource value: 0x7f0a006b
			public const int progressBar1 = 2131361899;
			
			// aapt resource value: 0x7f0a0059
			public const int rateBtn = 2131361881;
			
			// aapt resource value: 0x7f0a001f
			public const int relativeLayout1 = 2131361823;
			
			// aapt resource value: 0x7f0a005d
			public const int relativeLayout111 = 2131361885;
			
			// aapt resource value: 0x7f0a006a
			public const int relativeLayout2 = 2131361898;
			
			// aapt resource value: 0x7f0a005c
			public const int scaleImageView = 2131361884;
			
			// aapt resource value: 0x7f0a0090
			public const int searchLayout = 2131361936;
			
			// aapt resource value: 0x7f0a0099
			public const int sendEmail = 2131361945;
			
			// aapt resource value: 0x7f0a009a
			public const int sendSMS = 2131361946;
			
			// aapt resource value: 0x7f0a0066
			public const int shareBigDaysBtn = 2131361894;
			
			// aapt resource value: 0x7f0a0075
			public const int shopping = 2131361909;
			
			// aapt resource value: 0x7f0a0072
			public const int showListButton = 2131361906;
			
			// aapt resource value: 0x7f0a0005
			public const int small = 2131361797;
			
			// aapt resource value: 0x7f0a005a
			public const int tellFriends = 2131361882;
			
			// aapt resource value: 0x7f0a0055
			public const int textFacebookDescription = 2131361877;
			
			// aapt resource value: 0x7f0a0054
			public const int textFacebookName = 2131361876;
			
			// aapt resource value: 0x7f0a000a
			public const int textView1 = 2131361802;
			
			// aapt resource value: 0x7f0a0080
			public const int textView2 = 2131361920;
			
			// aapt resource value: 0x7f0a002a
			public const int textView3 = 2131361834;
			
			// aapt resource value: 0x7f0a0083
			public const int textView4 = 2131361923;
			
			// aapt resource value: 0x7f0a002d
			public const int textView5 = 2131361837;
			
			// aapt resource value: 0x7f0a0030
			public const int textView7 = 2131361840;
			
			// aapt resource value: 0x7f0a0033
			public const int textView9 = 2131361843;
			
			// aapt resource value: 0x7f0a0082
			public const int timeEdit = 2131361922;
			
			// aapt resource value: 0x7f0a007e
			public const int toolbar = 2131361918;
			
			// aapt resource value: 0x7f0a0006
			public const int toolbarAlerts = 2131361798;
			
			// aapt resource value: 0x7f0a0058
			public const int toolbarFeedback = 2131361880;
			
			// aapt resource value: 0x7f0a0067
			public const int toolbarList = 2131361895;
			
			// aapt resource value: 0x7f0a004e
			public const int toolbarSelDefImg = 2131361870;
			
			// aapt resource value: 0x7f0a0096
			public const int toolbarSelectRepeat = 2131361942;
			
			// aapt resource value: 0x7f0a0098
			public const int toolbarShare = 2131361944;
			
			// aapt resource value: 0x7f0a006e
			public const int trialMainImg = 2131361902;
			
			// aapt resource value: 0x7f0a0052
			public const int txtMessage = 2131361874;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alerts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BigDaysListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BigDaysListItemTrial = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_friendpickerfragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_login_activity_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_activity_circle_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_checkbox = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_image = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_list_row = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_list_section_header = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_picker_search_box = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_picker_title_bar = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_picker_title_bar_stub = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_placepickerfragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_placepickerfragment_list_row = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_facebook_search_bar_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int com_facebook_tooltip_bubble = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int com_facebook_usersettingsfragment = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int DefaultImagesSelect = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int FacebookScreen = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Feedback = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ImagePreview = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int InfoBoxViewControl = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int List = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LoadAppScreen = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Main = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NewBigDays = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NumberPickerDlg = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int PixabayImageGrid = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int PixabayImageGridItem = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int RepeatSelect = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Share = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int toolbar = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f040026
			public const int adBuddiz_api_key = 2130968614;
			
			// aapt resource value: 0x7f040029
			public const int adMob_api_interstitial_key = 2130968617;
			
			// aapt resource value: 0x7f040027
			public const int adMob_api_key = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int adMob_tracker_id = 2130968616;
			
			// aapt resource value: 0x7f04002a
			public const int app_name = 2130968618;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f04002b
			public const int cancelled = 2130968619;
			
			// aapt resource value: 0x7f040018
			public const int com_facebook_choose_friends = 2130968600;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_dialogloginactivity_ok_button = 2130968585;
			
			// aapt resource value: 0x7f04001c
			public const int com_facebook_internet_permission_error_message = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int com_facebook_internet_permission_error_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int com_facebook_loading = 2130968602;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_loginview_cancel_action = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_loginview_log_in_button = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_loginview_log_out_action = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_loginview_log_out_button = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_loginview_logged_in_as = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int com_facebook_logo_content_description = 2130968592;
			
			// aapt resource value: 0x7f040019
			public const int com_facebook_nearby = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int com_facebook_picker_done_button_text = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int com_facebook_placepicker_subtitle_format = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2130968598;
			
			// aapt resource value: 0x7f04001f
			public const int com_facebook_requesterror_password_changed = 2130968607;
			
			// aapt resource value: 0x7f040021
			public const int com_facebook_requesterror_permissions = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int com_facebook_requesterror_reconnect = 2130968608;
			
			// aapt resource value: 0x7f04001e
			public const int com_facebook_requesterror_relogin = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int com_facebook_requesterror_web_login = 2130968605;
			
			// aapt resource value: 0x7f040022
			public const int com_facebook_tooltip_default = 2130968610;
			
			// aapt resource value: 0x7f040011
			public const int com_facebook_usersettingsfragment_log_in_button = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int com_facebook_usersettingsfragment_logged_in = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int com_facebook_usersettingsfragment_not_logged_in = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f04003b
			public const int descr_image = 2130968635;
			
			// aapt resource value: 0x7f040030
			public const int error = 2130968624;
			
			// aapt resource value: 0x7f04003a
			public const int exception = 2130968634;
			
			// aapt resource value: 0x7f040039
			public const int facebook_app_id_amazon = 2130968633;
			
			// aapt resource value: 0x7f040038
			public const int facebook_app_id_debug = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int facebook_app_id_free = 2130968631;
			
			// aapt resource value: 0x7f040036
			public const int facebook_app_id_full = 2130968630;
			
			// aapt resource value: 0x7f040023
			public const int leadbolt_api_key = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int leadbolt_baner = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int leadbolt_interstitial = 2130968613;
			
			// aapt resource value: 0x7f040033
			public const int no_friends_selected = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int no_place_selected = 2130968628;
			
			// aapt resource value: 0x7f04002d
			public const int ok = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int permission_not_granted = 2130968620;
			
			// aapt resource value: 0x7f040035
			public const int pick_seattle_place = 2130968629;
			
			// aapt resource value: 0x7f040031
			public const int status_update = 2130968625;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			// aapt resource value: 0x7f04002e
			public const int success = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int successfully_posted_post = 2130968623;
			
			// aapt resource value: 0x7f040032
			public const int you_picked = 2130968626;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int ActionBarStyle = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int CustomActionBarTheme = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int CustomActionBarTheme_ImagePreview = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int ProgressBarStyle = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Theme_Splash = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_loginview_default_style = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_loginview_silver_style = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tooltip_bubble_text = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771981};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
