#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BigDays.Resource", IsApplication=true)]

namespace BigDays
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_blue = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_text_color = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_picker_search_bar_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_picker_search_bar_text = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loginview_compound_drawable_padding = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_loginview_padding_bottom = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_loginview_padding_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_loginview_padding_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_loginview_padding_top = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_text_size = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_picker_divider_width = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_picker_place_image_size = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_profilepictureview_preset_size_large = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_profilepictureview_preset_size_normal = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_profilepictureview_preset_size_small = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_tooltip_horizontal_padding = 2130968589;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AdBannerDefault = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AddBig = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AddSmall = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int alertbtnbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ArrowRight = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BackgroundLight = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Big_Day_Countdown_icon_app_1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Big_Day_Countdown_icon_appSmail = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Big_Day_Countdown_icon_appSupper_99_99 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int border_buttons = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_custom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int buynow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int colorChart = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_blue = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_blue_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_blue_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_blue_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_check = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_button_check_off = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_button_check_on = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_button_grey_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_button_grey_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_button_grey_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_close = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_inverse_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_list_divider = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_list_section_header_background = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_loginbutton_silver = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_logo = 2130837534;
			
			// aapt resource value: 0x7f020078
			public const int com_facebook_picker_default_separator_color = 2130837624;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_picker_item_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_picker_list_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_picker_list_longpressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_picker_list_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_picker_list_selector = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_picker_list_selector_background_transition = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_picker_list_selector_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_picker_magnifier = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_picker_top_button = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_place_default_icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_profile_default_icon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_profile_picture_blank_portrait = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_profile_picture_blank_square = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_tooltip_black_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_tooltip_black_bottomnub = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_tooltip_black_topnub = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int com_facebook_tooltip_black_xout = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int com_facebook_tooltip_blue_background = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_tooltip_blue_bottomnub = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int com_facebook_tooltip_blue_topnub = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int com_facebook_tooltip_blue_xout = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int com_facebook_top_background = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int com_facebook_top_button = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Edit = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int editbtnbg = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int EditSmall = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Facebook = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Feedback = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int FeedbackSmall = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_about = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_accept = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_action_cancel = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_action_discard = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_action_download = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_action_edit = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_action_group = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_action_new = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_action_share = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_action_storage = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_action_view_as_list = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int icon = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Icon62 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int Icon99x99 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int img1 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int img10 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int img10small = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int img11 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int img11small = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int img12 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int img12small = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int img13 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int img13small = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int img14 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int img14small = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int img15 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int img15small = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int img16 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int img16small = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int img17 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int img17small = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int img1small = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int img2 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int img2small = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int img3 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int img3small = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int img4 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int img4small = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int img5 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int img5small = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int img6 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int img6small = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int img7 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int img7small = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int img8 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int img8small = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int img9 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int img9small = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int img_help_resize = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int List = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ListSmall = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int Mail = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int Message = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int rotate = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int Save = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int Share = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int ShareSmall = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int splashscreen = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int Twitter = 2130837623;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001e
			public const int AlertOk = 2131296286;
			
			// aapt resource value: 0x7f090085
			public const int Alerts = 2131296389;
			
			// aapt resource value: 0x7f09007b
			public const int BigDayName = 2131296379;
			
			// aapt resource value: 0x7f090065
			public const int BigDaysListView = 2131296357;
			
			// aapt resource value: 0x7f090083
			public const int CameraBtn = 2131296387;
			
			// aapt resource value: 0x7f090087
			public const int CancelOrDelete = 2131296391;
			
			// aapt resource value: 0x7f090026
			public const int CountDownDays = 2131296294;
			
			// aapt resource value: 0x7f090029
			public const int CountDownHours = 2131296297;
			
			// aapt resource value: 0x7f09002c
			public const int CountDownMin = 2131296300;
			
			// aapt resource value: 0x7f09002f
			public const int CountDownSec = 2131296303;
			
			// aapt resource value: 0x7f09004c
			public const int DefImagesGrid = 2131296332;
			
			// aapt resource value: 0x7f090024
			public const int EndDate = 2131296292;
			
			// aapt resource value: 0x7f090090
			public const int FacebookBtn = 2131296400;
			
			// aapt resource value: 0x7f090077
			public const int Feedback = 2131296375;
			
			// aapt resource value: 0x7f090021
			public const int ItemImage = 2131296289;
			
			// aapt resource value: 0x7f09006e
			public const int MainCountDownDays = 2131296366;
			
			// aapt resource value: 0x7f09006f
			public const int MainCountDownHours = 2131296367;
			
			// aapt resource value: 0x7f090070
			public const int MainCountDownMin = 2131296368;
			
			// aapt resource value: 0x7f090071
			public const int MainCountDownSec = 2131296369;
			
			// aapt resource value: 0x7f09006d
			public const int MainCountDownTitle = 2131296365;
			
			// aapt resource value: 0x7f090060
			public const int NewCountDownTitle = 2131296352;
			
			// aapt resource value: 0x7f09005f
			public const int NewInfoBox = 2131296351;
			
			// aapt resource value: 0x7f090079
			public const int NewInfoBoxControl = 2131296377;
			
			// aapt resource value: 0x7f090058
			public const int Report = 2131296344;
			
			// aapt resource value: 0x7f090086
			public const int SeveOrEdit = 2131296390;
			
			// aapt resource value: 0x7f090091
			public const int TwitterBtn = 2131296401;
			
			// aapt resource value: 0x7f090066
			public const int addBigDays = 2131296358;
			
			// aapt resource value: 0x7f09001d
			public const int addNewBigDays = 2131296285;
			
			// aapt resource value: 0x7f090019
			public const int alertFiveInd = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int alertFiveIndTitle = 2131296280;
			
			// aapt resource value: 0x7f09001a
			public const int alertFiveNum = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int alertFiveStr = 2131296283;
			
			// aapt resource value: 0x7f090015
			public const int alertForeInd = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int alertForeIndTitle = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int alertForeNum = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int alertForeStr = 2131296279;
			
			// aapt resource value: 0x7f090009
			public const int alertOneInd = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int alertOneIndTitle = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int alertOneNum = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int alertOneStr = 2131296267;
			
			// aapt resource value: 0x7f090011
			public const int alertThreeInd = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int alertThreeIndTitle = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int alertThreeNum = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int alertThreeStr = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public const int alertTwoInd = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int alertTwoIndTitle = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int alertTwoNum = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int alertTwoStr = 2131296271;
			
			// aapt resource value: 0x7f09005c
			public const int btnRotate = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int btnSave = 2131296349;
			
			// aapt resource value: 0x7f090089
			public const int button1 = 2131296393;
			
			// aapt resource value: 0x7f09008a
			public const int button2 = 2131296394;
			
			// aapt resource value: 0x7f090043
			public const int com_facebook_body_frame = 2131296323;
			
			// aapt resource value: 0x7f090045
			public const int com_facebook_button_xout = 2131296325;
			
			// aapt resource value: 0x7f090033
			public const int com_facebook_login_activity_progress_bar = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int com_facebook_picker_activity_circle = 2131296306;
			
			// aapt resource value: 0x7f090035
			public const int com_facebook_picker_checkbox = 2131296309;
			
			// aapt resource value: 0x7f090039
			public const int com_facebook_picker_checkbox_stub = 2131296313;
			
			// aapt resource value: 0x7f09003d
			public const int com_facebook_picker_divider = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int com_facebook_picker_done_button = 2131296316;
			
			// aapt resource value: 0x7f090036
			public const int com_facebook_picker_image = 2131296310;
			
			// aapt resource value: 0x7f09003a
			public const int com_facebook_picker_list_section_header = 2131296314;
			
			// aapt resource value: 0x7f090031
			public const int com_facebook_picker_list_view = 2131296305;
			
			// aapt resource value: 0x7f090037
			public const int com_facebook_picker_profile_pic_stub = 2131296311;
			
			// aapt resource value: 0x7f090034
			public const int com_facebook_picker_row_activity_circle = 2131296308;
			
			// aapt resource value: 0x7f090042
			public const int com_facebook_picker_search_text = 2131296322;
			
			// aapt resource value: 0x7f090038
			public const int com_facebook_picker_title = 2131296312;
			
			// aapt resource value: 0x7f09003f
			public const int com_facebook_picker_title_bar = 2131296319;
			
			// aapt resource value: 0x7f09003e
			public const int com_facebook_picker_title_bar_stub = 2131296318;
			
			// aapt resource value: 0x7f09003b
			public const int com_facebook_picker_top_bar = 2131296315;
			
			// aapt resource value: 0x7f090041
			public const int com_facebook_search_bar_view = 2131296321;
			
			// aapt resource value: 0x7f090047
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296327;
			
			// aapt resource value: 0x7f090046
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296326;
			
			// aapt resource value: 0x7f090044
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296324;
			
			// aapt resource value: 0x7f09004a
			public const int com_facebook_usersettingsfragment_login_button = 2131296330;
			
			// aapt resource value: 0x7f090048
			public const int com_facebook_usersettingsfragment_logo_image = 2131296328;
			
			// aapt resource value: 0x7f090049
			public const int com_facebook_usersettingsfragment_profile_name = 2131296329;
			
			// aapt resource value: 0x7f09007d
			public const int dateEdit = 2131296381;
			
			// aapt resource value: 0x7f090081
			public const int defImagesBtn = 2131296385;
			
			// aapt resource value: 0x7f090062
			public const int editBigDaysBtn = 2131296354;
			
			// aapt resource value: 0x7f090084
			public const int editRepeat = 2131296388;
			
			// aapt resource value: 0x7f09004e
			public const int facebook_login_button = 2131296334;
			
			// aapt resource value: 0x7f090054
			public const int fragment_container = 2131296340;
			
			// aapt resource value: 0x7f09005e
			public const int helpRelaLayout = 2131296350;
			
			// aapt resource value: 0x7f090080
			public const int imageArea = 2131296384;
			
			// aapt resource value: 0x7f090050
			public const int imageView1 = 2131296336;
			
			// aapt resource value: 0x7f09006c
			public const int infoBox = 2131296364;
			
			// aapt resource value: 0x7f09001f
			public const int infoBoxListItem = 2131296287;
			
			// aapt resource value: 0x7f090000
			public const int large = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout1 = 2131296260;
			
			// aapt resource value: 0x7f090072
			public const int linearLayout10 = 2131296370;
			
			// aapt resource value: 0x7f090061
			public const int linearLayout11 = 2131296353;
			
			// aapt resource value: 0x7f090073
			public const int linearLayout12 = 2131296371;
			
			// aapt resource value: 0x7f090074
			public const int linearLayout13 = 2131296372;
			
			// aapt resource value: 0x7f09005b
			public const int linearLayout1311 = 2131296347;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout2 = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout3 = 2131296261;
			
			// aapt resource value: 0x7f090025
			public const int linearLayout4 = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int linearLayout5 = 2131296296;
			
			// aapt resource value: 0x7f09002b
			public const int linearLayout6 = 2131296299;
			
			// aapt resource value: 0x7f09002e
			public const int linearLayout7 = 2131296302;
			
			// aapt resource value: 0x7f090020
			public const int linearLayout8 = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int linearLayout9 = 2131296290;
			
			// aapt resource value: 0x7f09008c
			public const int listRepeat = 2131296396;
			
			// aapt resource value: 0x7f090076
			public const int mainAddBigDays = 2131296374;
			
			// aapt resource value: 0x7f09006a
			public const int mainImgBase = 2131296362;
			
			// aapt resource value: 0x7f090069
			public const int main_layout = 2131296361;
			
			// aapt resource value: 0x7f09004d
			public const int main_ui_container = 2131296333;
			
			// aapt resource value: 0x7f090023
			public const int name = 2131296291;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090088
			public const int numberPicker1 = 2131296392;
			
			// aapt resource value: 0x7f090082
			public const int photo_AlbumBtn = 2131296386;
			
			// aapt resource value: 0x7f090040
			public const int picker_subtitle = 2131296320;
			
			// aapt resource value: 0x7f090053
			public const int postStatusUpdateButton = 2131296339;
			
			// aapt resource value: 0x7f090068
			public const int progressBar1 = 2131296360;
			
			// aapt resource value: 0x7f090056
			public const int rateBtn = 2131296342;
			
			// aapt resource value: 0x7f09001c
			public const int relativeLayout1 = 2131296284;
			
			// aapt resource value: 0x7f09005a
			public const int relativeLayout111 = 2131296346;
			
			// aapt resource value: 0x7f090067
			public const int relativeLayout2 = 2131296359;
			
			// aapt resource value: 0x7f090059
			public const int scaleImageView = 2131296345;
			
			// aapt resource value: 0x7f09008e
			public const int sendEmail = 2131296398;
			
			// aapt resource value: 0x7f09008f
			public const int sendSMS = 2131296399;
			
			// aapt resource value: 0x7f090063
			public const int shareBigDaysBtn = 2131296355;
			
			// aapt resource value: 0x7f090078
			public const int shopping = 2131296376;
			
			// aapt resource value: 0x7f090075
			public const int showListButton = 2131296373;
			
			// aapt resource value: 0x7f090002
			public const int small = 2131296258;
			
			// aapt resource value: 0x7f090057
			public const int tellFriends = 2131296343;
			
			// aapt resource value: 0x7f090052
			public const int textFacebookDescription = 2131296338;
			
			// aapt resource value: 0x7f090051
			public const int textFacebookName = 2131296337;
			
			// aapt resource value: 0x7f090007
			public const int textView1 = 2131296263;
			
			// aapt resource value: 0x7f09007c
			public const int textView2 = 2131296380;
			
			// aapt resource value: 0x7f090027
			public const int textView3 = 2131296295;
			
			// aapt resource value: 0x7f09007f
			public const int textView4 = 2131296383;
			
			// aapt resource value: 0x7f09002a
			public const int textView5 = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int textView7 = 2131296301;
			
			// aapt resource value: 0x7f090030
			public const int textView9 = 2131296304;
			
			// aapt resource value: 0x7f09007e
			public const int timeEdit = 2131296382;
			
			// aapt resource value: 0x7f09007a
			public const int toolbar = 2131296378;
			
			// aapt resource value: 0x7f090003
			public const int toolbarAlerts = 2131296259;
			
			// aapt resource value: 0x7f090055
			public const int toolbarFeedback = 2131296341;
			
			// aapt resource value: 0x7f090064
			public const int toolbarList = 2131296356;
			
			// aapt resource value: 0x7f09004b
			public const int toolbarSelDefImg = 2131296331;
			
			// aapt resource value: 0x7f09008b
			public const int toolbarSelectRepeat = 2131296395;
			
			// aapt resource value: 0x7f09008d
			public const int toolbarShare = 2131296397;
			
			// aapt resource value: 0x7f09006b
			public const int trialMainImg = 2131296363;
			
			// aapt resource value: 0x7f09004f
			public const int txtMessage = 2131296335;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alerts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BigDaysListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BigDaysListItemTrial = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_friendpickerfragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_login_activity_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_activity_circle_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_checkbox = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_image = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_list_row = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_list_section_header = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_picker_search_box = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_picker_title_bar = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_picker_title_bar_stub = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_placepickerfragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_placepickerfragment_list_row = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_facebook_search_bar_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int com_facebook_tooltip_bubble = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int com_facebook_usersettingsfragment = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int DefaultImagesSelect = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int FacebookScreen = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Feedback = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ImagePreview = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int InfoBoxViewControl = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int List = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LoadAppScreen = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Main = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NewBigDays = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NumberPickerDlg = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int RepeatSelect = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Share = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int toolbar = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001d
			public const int adBuddiz_api_key = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int adMob_api_key = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int app_name = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int cancelled = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_choose_friends = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_dialogloginactivity_ok_button = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_internet_permission_error_message = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_internet_permission_error_title = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_loading = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_cancel_action = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_loginview_log_in_button = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_loginview_log_out_action = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_loginview_log_out_button = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_loginview_logged_in_as = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_loginview_logged_in_using_facebook = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_logo_content_description = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_nearby = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_picker_done_button_text = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_placepicker_subtitle_format = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_requesterror_password_changed = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_requesterror_permissions = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_requesterror_reconnect = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_requesterror_relogin = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_requesterror_web_login = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int com_facebook_tooltip_default = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_usersettingsfragment_log_in_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_usersettingsfragment_logged_in = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131099658;
			
			// aapt resource value: 0x7f060025
			public const int error = 2131099685;
			
			// aapt resource value: 0x7f06002f
			public const int exception = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int facebook_app_id_amazon = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int facebook_app_id_debug = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int facebook_app_id_free = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int facebook_app_id_full = 2131099691;
			
			// aapt resource value: 0x7f06001a
			public const int leadbolt_api_key = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int leadbolt_baner = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int leadbolt_interstitial = 2131099676;
			
			// aapt resource value: 0x7f060028
			public const int no_friends_selected = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int no_place_selected = 2131099689;
			
			// aapt resource value: 0x7f060022
			public const int ok = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int permission_not_granted = 2131099681;
			
			// aapt resource value: 0x7f06002a
			public const int pick_seattle_place = 2131099690;
			
			// aapt resource value: 0x7f060026
			public const int status_update = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int success = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int successfully_posted_post = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int you_picked = 2131099687;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int ActionBarStyle = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int CustomActionBarTheme = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int CustomActionBarTheme_ImagePreview = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int Theme_Splash = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_loginview_default_style = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_loginview_silver_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int tooltip_bubble_text = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
